AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DBHost:
    Type: String
    Description: Database Host URL

  DBUser:
    Type: String
    Description: Database Username

  DBPassword:
    Type: String
    Description: Database Password

  DBDatabase:
    Type: String
    Description: Database Name

  DBPort:
    Type: String
    Description: Database Port

  AWSRegion:
    Type: String
    Description: AWS Region for the resources

  CognitoUserPoolId:
    Type: String
    Description: ID of the Cognito User Pool

  CognitoClientId:
    Type: String
    Description: Cognito Client ID

  ImageURL:
    Type: String
    Default: public.ecr.aws/u0t4o1i1/playpal_usercreation_service:latest
    Description: Docker image URL for the container

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-task-definition
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: "arn:aws:iam::429647661750:role/ECSTaskExecutionRole"
      TaskRoleArn: "arn:aws:iam::429647661750:role/ECSTaskRole"
      Cpu: "256"
      Memory: "512"
      ContainerDefinitions:
        - Name: my-container
          Image: !Ref ImageURL
          Essential: true
          PortMappings:
            - ContainerPort: 3001
          Environment:
            - Name: DB_HOST
              Value: !Ref DBHost
            - Name: DB_USER
              Value: !Ref DBUser
            - Name: DB_PASS
              Value: !Ref DBPassword
            - Name: DB_DB
              Value: !Ref DBDatabase
            - Name: DB_PORT
              Value: !Ref DBPort
            - Name: AWS_REGION
              Value: !Ref AWSRegion
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref CognitoUserPoolId
            - Name: COGNITO_CLIENT_ID
              Value: !Ref CognitoClientId
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: Playpal_Usercreation
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: cfn-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-0e6b3a491f1baa1b1
          Subnets:
            - subnet-0708f044a8938f706

